language: d

d: dmd

# No Mac support until Metal is implemented.
os:
  - linux

sudo: false

addons:
  apt:
    sources: &native_sources
      - kubuntu-backports # GLFW CMake version.

    packages: &native_deps
      - gcc-multilib  # unittest-cov support.
      - g++-multilib  # Assimp support.
      - cmake         # GLFW.

matrix:
  include:

    # 32-bit DMD
    - env: ARCH=x86
      d: dmd-2.072.2
      addons:
        apt:
          sources: *native_sources
          packages:
            - *native_deps
            - &32bit_deps ["libx11-dev:i386", "libxrandr-dev:i386", "libxinerama-dev:i386", "libxcursor-dev:i386",
                           "libxfixes-dev:i386", "libxext-dev:i386", "libgl1-mesa-dev:i386", "libglu1-mesa-dev:i386"]

    # 32-bit LDC2
    - env: ARCH=x86
      d: ldc-1.2.0
      addons:
        apt:
          sources: *native_sources
          packages:
            - *native_deps
            - *32bit_deps

    # 32-bit GDC
    - env: ARCH=x86
      d: gdc
      addons:
        apt:
          sources: *native_sources
          packages:
            - *native_deps
            - *32bit_deps

    # 64-bit DMD
    - env: ARCH=x86_64
      d: dmd-2.072.2
      addons:
        apt:
          sources: *native_sources
          packages:
            - *native_deps
            - &64bit_deps [libx11-dev, libxrandr-dev, libxinerama-dev, libxcursor-dev]

    # 64-bit LDC2
    - env: ARCH=x86_64
      d: ldc-1.2.0
      addons:
        apt:
          sources: *native_sources
          packages:
            - *native_deps
            - *64bit_deps

    # 64-bit GDC
    - env: ARCH=x86_64
      d: gdc
      addons:
        apt:
          sources: *native_sources
          packages:
            - *native_deps
            - *64bit_deps

  allow_failures:
    - d: gdc
      
  exclude:
    - d: dmd
    
install:
  - dub fetch doveralls
  - dub build doveralls

script:
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:.:./builds
  - ./build.sh build debug $ARCH ${DC}
  - ./build.sh build optimized $ARCH ${DC}
  - ./build.sh build release $ARCH ${DC}
  - ./build.sh build release-nobounds $ARCH ${DC}
  - ./build.sh test unittest-cov $ARCH ${DC}
  - ./build.sh test unittest-optimized $ARCH ${DC}

after_script:
  - dub run doveralls
