language: d

# No Mac support until Metal is implemented.
os:
  - linux
#  - osx

sudo: false

d:
  - dmd
  - ldc2
  - gdc

matrix:
  allow_failures:
    - os: linux
      d: gdc

addons:
  apt:
    sources:
      - kubuntu-backports # GLFW CMake version.
    packages:
      - gcc-multilib          # unittest-cov support.
      - cmake                 # GLFW.
      - libx11-dev:i386       # GLFW.
      - libxau-dev       # GLFW.
      - libxcursor-dev   # GLFW.
      - libxdmcp-dev     # GLFW.
      - libxext-dev      # GLFW.
      - libxfixes-dev    # GLFW.
      - libxinerama-dev  # GLFW.
      - libxrandr-dev    # GLFW.
      - libxrender-dev   # GLFW.
    
install:
  - dub fetch doveralls
  - dub build doveralls

# 64-bit only support on Linux using GDC until a more permanent solution to not having a 32-bit phobos can be found.
script:
  - if [ "$DC" != "gdc" ]; then dub test --arch=x86 --build=unittest; fi
  - if [ "$DC" != "gdc" ]; then dub test --arch=x86 --build=optimized-unittest; fi
  - if [ "$DC" != "gdc" ]; then dub test --arch=x86 --build=release-unittest; fi
  - dub test --arch=x86_64 --build=unittest-cov
  - dub test --arch=x86_64 --build=optimized-unittest
  - dub test --arch=x86_64 --build=release-unittest

after_script:
  - dub run doveralls